# Generated by Django 4.1.3 on 2022-11-12 02:43

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=django_cryptography.fields.encrypt(models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='card',
            name='fp',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, unique=True)),
        ),
    ]
