# Generated by Django 4.1.3 on 2022-11-12 02:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0002_alter_card_amount_alter_card_fp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=250)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_path',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, unique=True)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50, unique=True)),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_price',
            field=django_cryptography.fields.encrypt(models.IntegerField()),
        ),
    ]
